name: pulseaudio-example
version: '1'
summary: Snap to test pulseaudio in Core
description: |
  Snap to test pulseaudio in Core
base: core18
grade: stable
confinement: strict

apps:
  pulseaudio-example:
    command: bin/client-wrapper usr/bin/pulseaudio-example
    plugs:
      - audio-playback
      - home

parts:
  pulseaudio-example-common:
    plugin: dump
    source: overlay

  pulseaudio-example:
    plugin: cmake
    source: src
    build-packages:
      - build-essential
      - libpulse-dev
